# Phân tích tĩnh mạnh mẽ hơn
analyzer:
  strong-mode:
    implicit-casts: false       # Không cho phép ép kiểu ngầm định (an toàn hơn)
    implicit-dynamic: false     # Không cho phép kiểu 'dynamic' ngầm định

  errors:
    # Coi các vi phạm quan trọng là lỗi đỏ luôn, không chỉ là cảnh báo vàng
    missing_required_param: error
    missing_return: error
    todo: ignore             # Bỏ qua cảnh báo TODO (để đỡ rối mắt)
    invalid_assignment: error

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # --- STYLE & CONSISTENCY ---
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_locals: true
    sort_child_properties_last: true
    sized_box_for_whitespace: true
    directives_ordering: true
    
    # --- SAFETY & BUGS ---
    avoid_print: true          # Nên tắt khi dev, bật khi chuẩn bị release
    unawaited_futures: true
    avoid_void_async: true
    cancel_subscriptions: true
    close_sinks: true
    always_declare_return_types: true
    library_private_types_in_public_api: true
    use_build_context_synchronously: true
    
    # --- OTHERS ---
    require_trailing_commas: true # Rất hữu ích cho Flutter UI code dễ đọc hơn