// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXd5X5YZfrM720BlnZQwLNMOSUXwPFi8w',
    appId: '1:160608226091:web:3ebcf779a0dea5ebc6936e',
    messagingSenderId: '160608226091',
    projectId: 'cat1m-flutter-demo',
    authDomain: 'cat1m-flutter-demo.firebaseapp.com',
    storageBucket: 'cat1m-flutter-demo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSS_QwRQ08LwGvrQnVeHfCQEHwlJhZTWo',
    appId: '1:160608226091:android:e68c416fc1d6b320c6936e',
    messagingSenderId: '160608226091',
    projectId: 'cat1m-flutter-demo',
    storageBucket: 'cat1m-flutter-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvUv6YQ6hSWJxfG9R9OqyexB3YL7mW8Pw',
    appId: '1:160608226091:ios:0447f4fca5c9939fc6936e',
    messagingSenderId: '160608226091',
    projectId: 'cat1m-flutter-demo',
    storageBucket: 'cat1m-flutter-demo.firebasestorage.app',
    iosBundleId: 'com.example.reqresIn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvUv6YQ6hSWJxfG9R9OqyexB3YL7mW8Pw',
    appId: '1:160608226091:ios:0447f4fca5c9939fc6936e',
    messagingSenderId: '160608226091',
    projectId: 'cat1m-flutter-demo',
    storageBucket: 'cat1m-flutter-demo.firebasestorage.app',
    iosBundleId: 'com.example.reqresIn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXd5X5YZfrM720BlnZQwLNMOSUXwPFi8w',
    appId: '1:160608226091:web:d37aed81f47409e3c6936e',
    messagingSenderId: '160608226091',
    projectId: 'cat1m-flutter-demo',
    authDomain: 'cat1m-flutter-demo.firebaseapp.com',
    storageBucket: 'cat1m-flutter-demo.firebasestorage.app',
  );
}
