// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Sinh khoá AES-256 ngẫu nhiên (base64), dùng để lưu ở SecureStorage phía Dart.
String generateKey() => RustLib.instance.api.crateApiCryptoGenerateKey();

/// Mã hoá `plaintext` bằng AES-256-GCM với khoá `key_b64` (base64).
String encrypt({required String keyB64, required String plaintext}) => RustLib
    .instance
    .api
    .crateApiCryptoEncrypt(keyB64: keyB64, plaintext: plaintext);

/// Giải mã payload sinh ra bởi [`encrypt`].
String decrypt({required String keyB64, required String payloadB64}) => RustLib
    .instance
    .api
    .crateApiCryptoDecrypt(keyB64: keyB64, payloadB64: payloadB64);
