// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Sinh salt ngẫu nhiên (base64) dùng cho việc derive khoá từ PIN.
String generateSalt() => RustLib.instance.api.crateApiKdfGenerateSalt();

/// Derive khoá AES-256 (base64) từ PIN + salt bằng Argon2id.
/// Cố tình KHÔNG đánh dấu `frb(sync)` — Argon2 chậm có chủ đích (chống
/// brute-force), nếu chạy sync sẽ chặn UI thread. Để async, flutter_rust_bridge
/// tự chạy hàm này trên 1 thread nền, Dart nhận về Future thay vì bị block.
Future<String> deriveKey({required String pin, required String saltB64}) =>
    RustLib.instance.api.crateApiKdfDeriveKey(pin: pin, saltB64: saltB64);
